server:
  port: 7890
  # gzip压缩
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/xml, text/plain
    min-response-size: 4096
  undertow:
    accesslog:
      dir: undertow-log
      enabled: false
      pattern: common
      prefix: access_log
      suffix: .log
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    direct-buffers: true
    # HTTP POST请求最大的大小
    max-http-post-size: 0

com:
  example:
    blog:
      name: name in dev

spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: html
    cache: false

  messages:
    fallbackToSystemLocale: false
    # 文件名
    basename: i18n/reserved, i18n/message

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:6543/my_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

      #监控页相对路径 druid
      stat-view-servlet:
        login-username: mmc
        login-password: 123456

  jooq:
    sql-dialect: postgres

  jpa:
    properties:
      hibernate:
        temp: # 避免启动的时候崩溃
          use_jdbc_metadata_defaults: false
    # 这个用于自动建表
    hibernate:
      ddl-auto: create

logging:
  file: logs/log.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    com.mmc.springbootdemo: DEBUG

pagehelper:
  helper-dialect: postgresql

shiro:
  loginUrl: /login.html
  shiro.successUrl: /login_success.html
  shiro.unauthorizedUrl: /login.html

mybatis:
  mapper-locations: "classpath*:**/**Mapper.xml"