server:
  port: 7777

com:
  example:
    blog:
      name: name in test

spring:
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://127.0.0.1:6543/my_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

      #监控页相对路径 druid
      stat-view-servlet:
        login-username: mmc
        login-password: 123456

  jpa:
    properties:
      hibernate:
        temp:
          #解决spring boot的这个报错信息：这个 org.postgresql.jdbc.PgConnection.createClob() 方法尚未被实作。
          use_jdbc_metadata_defaults: false